package TemplateMethod;

public class DemoAppTemplate {

    public static void main(String[] args) {
        System.out.println("------------------------------");
        System.out.println("For MYSQL....");
        ConnectionTemplate template = new MySqLCSVCon();
        template.run();
        System.out.println("------------------------------");
        System.out.println("For Oracle...");
        template = new OracleTxtCon();
        template.run();
        System.out.println("------------------------------");
    }
}

/* РЕЗУЛЬТАТ:

------------------------------
For MYSQL....
Setting MySQL DB drivers...
Setting credentials for MySQL DB...
Setting connection...
Preparing insert statement...
Setting up data from csv file....
Inserting data...
Closing connections...
Destroying connection objects...
------------------------------
For Oracle...
Setting Oracle DB drivers...
Logging....: Drivers set [Sun Jul 11 17:58:22 EET 2021]
Setting credentials for Oracle DB...
Logging....: Credentails set [Sun Jul 11 17:58:22 EET 2021]
Setting connection...
Logging....: Conencted
Preparing insert statement...
Logging....: Statement prepared [Sun Jul 11 17:58:22 EET 2021]
Setting up data from txt file....
Logging....: Data set [Sun Jul 11 17:58:22 EET 2021]
Inserting data...
Logging....: Inserted [Sun Jul 11 17:58:22 EET 2021]
Closing connections...
Logging....: Conenctions closed [Sun Jul 11 17:58:22 EET 2021]
Destroying connection objects...
Logging....: Object destoryed [Sun Jul 11 17:58:22 EET 2021]
------------------------------

 */